friends/config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :registros
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

friends/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

friends/app/models/registro.rb
class Registro < ApplicationRecord
end

friends/app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

friends/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

friends/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

friends/app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :set_registro, only: %i[ show edit update destroy ]

  # GET /registros or /registros.json
  def index
    @registros = Registro.all
  end

  # GET /registros/1 or /registros/1.json
  def show
  end

  # GET /registros/new
  def new
    @registro = Registro.new
  end

  # GET /registros/1/edit
  def edit
  end

  # POST /registros or /registros.json
  def create
    @registro = Registro.new(registro_params)

    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: "Registro was successfully created." }
        format.json { render :show, status: :created, location: @registro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registros/1 or /registros/1.json
  def update
    respond_to do |format|
      if @registro.update(registro_params)
        format.html { redirect_to @registro, notice: "Registro was successfully updated." }
        format.json { render :show, status: :ok, location: @registro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registros/1 or /registros/1.json
  def destroy
    @registro.destroy
    respond_to do |format|
      format.html { redirect_to registros_url, notice: "Registro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro
      @registro = Registro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def registro_params
      params.require(:registro).permit(:nombre, :apellido, :correo, :telefono, :usuario)
    end
end

friends/app/helpers/application_helper.rb
module ApplicationHelper
end

friends/app/helpers/home_helper.rb
module HomeHelper
end

friends/app/helpers/registros_helper.rb
module RegistrosHelper
end

friends/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Aplicacion",root_path,class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "Acerca de..",home_about_path,class:"nav-link" %>
      </li>
      <% if usuario_signed_in? %>
        <li class="nav-item">
          <%= link_to "Registros",registros_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Modificar perfil",edit_usuario_registration_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out",destroy_usuario_session_path,method: :DELETE,class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Registrarse",new_usuario_registration_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log In",new_usuario_session_path,class:"nav-link" %>
        </li>
      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

friends/app/views/home/about.html.erb
<h1>Acerca de</h1>
<p>En ruby 2</p>

friends/app/views/home/index.html.erb
<h1>Twice es un fraude</h1>
<p>En ruby</p>

friends/app/views/layouts/_alerts.html.erb
</br>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

friends/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Pruebasss</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "home/header" %>
    
    <div class="container">
    <% if notice %>
      <%= render "layouts/alerts" %>
      <% end %>
    <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

friends/app/views/registros/_form.html.erb
<%= form_with(model: registro) do |form| %>
  <% if registro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(registro.errors.count, "error") %> prohibited this registro from being saved:</h2>

      <ul>
        <% registro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :apellido %>
    <%= form.text_field :apellido,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :correo %>
    <%= form.text_field :correo,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :telefono %>
    <%= form.text_field :telefono,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :usuario %>
    <%= form.text_field :usuario,class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

friends/app/views/registros/edit.html.erb
<h1>Editing Registro</h1>

<%= render 'form', registro: @registro %>

<br>

<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-light"><%= link_to 'Mostrar registro', @registro %> </button>
  <button type="button" class="btn btn-light"><%= link_to 'Regresar', registros_path %></button>
</div>

friends/app/views/registros/index.html.erb
<h1>Registros</h1>

<table class="table table-dark table-borderless">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Correo</th>
      <th>Telefono</th>
      <th>Usuario</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @registros.each do |registro| %>
      <tr>
        <td><%= registro.nombre %></td>
        <td><%= registro.apellido %></td>
        <td><%= registro.correo %></td>
        <td><%= registro.telefono %></td>
        <td>@<%= registro.usuario %></td>
        <td><button type="button" class="btn btn-light"><%= link_to 'Mostrar registro', registro %></button></td>
        <td><button type="button" class="btn btn-light"><%= link_to 'Editar registro', edit_registro_path(registro) %></button></td>
        <td><button type="button" class="btn btn-light"><%= link_to 'Eliminar registro', registro, method: :delete, data: { confirm: '¿Estás seguro de eliminar este registro?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-light"><%= link_to 'Dar de alta nuevo registro', new_registro_path %> </button>
</div>

friends/app/views/registros/new.html.erb
<h1>New Registro</h1>

<%= render 'form', registro: @registro %>

<br>
<%= link_to 'Regresar', registros_path,class:"btn btn-light" %>

friends/app/views/registros/show.html.erb
  <br>
<div class="jumbotron">
  <h1 class="display-4"><%= @registro.nombre %> <%= @registro.apellido %></h1>
  <hr class="my-4">
  <p><%= @registro.correo %> ■ <%= @registro.telefono %> ■ @<%= @registro.usuario %></p>

  <br>
  <div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-light"><%= link_to 'Editar registro', edit_registro_path(@registro) %> </button>
  <button type="button" class="btn btn-light"><%= link_to 'Regresar', registros_path %></button>
  </div>
</div>